language: java
jdk:
- oraclejdk8
script:
- mvn test -Dspring.profiles.active=travis -Dmaven.javadoc.skip=true
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: jI1pHQ/91hcuxe9brn2mv2LSA6D1t8et556hcG9HoVUkMdTz1r0vV9m4NFdT6dqJOTNXYME321mXsxuhihhXFAF+yvrevSQCiArHBC2j9WdzaygND/or9lzzJcQ05LRdWOuS6Sm1dn2KSwlWLjdfM3mzk9cRstzfKX0HsXk2YGiKfIflrZrg1jiOfBpgVgPxtjXGwiisJJW1QeYA1Q15p2G4uB5u8sy3+6Zl6tpC9hUjmRjsXzSpUMXj5gSxYn/sqtCrY4cA/RcWNRxZlGO5A6lyffHtiK4HLsk1j8+jJ9EJv2WUuXvWgdcSOejjYk/57X91iDc5WSmsteYHe+4NK0xweeIsByvP2BlVqD2yKkYBB6U8fH8YcDExh7Lb55P2AUS8kYDX0LXNpJUrjq3IzKsblE8+6L5VT1bPg2HsvBgLIPpEMksOysiuCVB5qxT8CCPOe/2b6KhZd5ii/g6vMhx6jD0w/joMLpOhETi75dgagbkeNws7HhQDDKHGXOwTfrqeUiw+bTJesxBI9XnGNDMqISKNfilm85UeDeO3WtXr359Lqh8Wpphs5O0WkBCi2zLxgUeoTmlg7XEegb2+qaYuFhnv1W2LddU8dSesQqBtuVs16Ud39uU/1577MtGbwVvtN75XheD2YFqk8Sc5sdRk9PnH+KECg5Lsf+bZ24s=
  app: hello-wrold
  on:
    repo: georgybagramyan/hello-world
