language: java
jdk:
- oraclejdk8
script:
- mvn test -Dspring.profiles.active=travis -Dmaven.javadoc.skip=true
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: a78JLQ2DtVNxhecUgfURbaRgqEv3fRm2KsT/EWEIxAmtgeTNl93e8wZJNuQI7jdLoQlMidmeiJlIMrYoHfdDVBL3BHtWSvnA2YvCWRSJKIYqKPbv9zAMuEOy4i3mhRgleCiEjPp0DwLUbbgC9tJtqSIcnGdvS3z8FwlRSPRcILsFK4MjZQCcMcge9r/hwOsiIXaakbniYVpbrmC0sQ6rpGrxFiD9vlRIichNA7L7JmIV3dS45uaIQVZ8m4JxhPLNZKnm1kuOfjXVOlOaWEZGzWWizp0zWKWmTMQf8M+MuFnNOSzWkcukeEJlHC4hXZSmrc6RZ2/6H2mT0wc5VDNvAOYY/daManjuhzYlwArl17wFwbjXppPFErTLVRCqx+kQszHSG3tFYsYmmFJPVu/PEvINvFCjr/eZEkLZAoKhpwilUnX2ZVSmHUgMZOUnlkoeMBy8+EU/h6epOQa++IkGDjzsqgu5m4nUr97PuJ9dNxd3/OJOPnvP3IXog3Kj9zs2tBL3GylwMNrWaLFv6YJOuPaxR2ZVQEEXli3zthv0dodgBTbLj0lTM/l89sduAh+fQ9yr/BNZDsoBI9qCoOJ9UhISF+KnapOiF5B2mlGBiNgRAnXD9HEn8WNYTaAa42EyEPlpNz2RKpDffhVZN4qAcPLIBS336Bmn4+25ey4ch5E=
