spring:
    profiles: production
    database:
        driverClassName: org.postgresql.Driver
    datasource:
        platform: postgres
        url: ${JDBC_DATABASE_URL}
        username: postgres
        password: postgres
    jpa:
        database: POSTGRESQL
        hibernate:
                    ddl-auto: create-drop
        show-sql: true

